apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: demo
    type: demo
    name: nginx-service
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
      env: demo
