apiVersion: v1
kind: Pod
metadata:
  name: nginx-prefer
  labels:
    env: dev
    type: demo
    name: nginx-pod
spec:
  containers:
    - name: nginx-prefer
      image: nginx:latest
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: diskType
                operator: In
                values:
                  - hdd