apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: dev
    type: demo
    name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"