apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce #it should have same as pv
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
