apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    env: demo
    type: demo
    name: nginx-deploy
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
        type: demo
        name: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      env: demo
