apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default # Must be in the same namespace as the Role
subjects:
  - kind: User
    name: adam # Replace with the actual username
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader # Must match the name of the Role
  apiGroup: rbac.authorization.k8s.io