apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-limit
spec:
  containers:
    - name: nginx-limit
      image: nginx:latest
      resources:
        requests:
          cpu: "50m"
          memory: "1Mi"
        limits:
          cpu: "100m"
          memory: "2Mi"